before_install: gem install bundler --pre
language: ruby
rvm:
  - 2.0.0
script: "bundle exec rake db:drop db:create db:migrate spec"
bundler_args: --without development --path vendor/bundle
gemfile:
  - Gemfile
branches:
  only:
    - master
env:
  - DB=sqlite3
