development: &development
  adapter: postgresql
  database: we_love_heroku_development
  encoding: utf8
test:
  <<: *development
  database: we_love_heroku_test
production:
  <<: *development
  database: we_love_heroku_production
staging:
  <<: *development
  database: we_love_heroku_staging
